# Generated by Django 3.1.5 on 2021-02-12 06:23

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title_format')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ZH', 'Chinese')], max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
    ]
