# Generated by Django 3.1.5 on 2021-02-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210208_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], max_length=2),
        ),
    ]
